[workspace]
members = [
    "meilies",
    "meilies-async-cli",
    "meilies-cli",
    "meilies-client",
    "meilies-inspect",
    "meilies-server",
    "meilies-transhumance",
]

[profile.release]
debug = true
