[package]
name = "meilies-server"
version = "0.1.1"
authors = ["Kerollmops <renault.cle@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6.0"
futures = "0.1.25"
log = "0.4.6"
meilies = { version = "0.1", path = "../meilies" }
sled = { version = "0.21.0", features = ["compression"] }
structopt = { version = "0.2.14", default-features = false }
tokio = "0.1.16"
tokio-threadpool = "0.1.12"
sentry = { version = "0.15.2", optional = true }
