[package]
name = "meilies-server"
version = "0.1.0"
authors = ["Kerollmops <renault.cle@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6.0"
futures = "0.1.25"
log = "0.4.6"
meilies = { version = "0.1", path = "../meilies" }
sled = "0.19.0"
tokio = "0.1.16"
tokio-threadpool = "0.1.12"
