[package]
name = "meilies-server"
description = "A Rust based event store server using the Redis protocol"
license = "MIT"
version = "0.1.0"
authors = ["Kerollmops <kero@meilisearch.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6.0"
futures = "0.1.25"
log = "0.4.6"
meilies = { version = "0.1", path = "../meilies" }
sled = "0.20.0"
structopt = { version = "0.2.14", default-features = false }
tokio = "0.1.16"
tokio-threadpool = "0.1.12"
sentry = { version = "0.15.2", optional = true }

[package.metadata.deb]
maintainer = "Kerollmops <kero@meilisearch.com>"
copyright = "2019, Kerollmops <kero@meilisearch.com>"
depends = "$auto, systemd"
section = "database"
priority = "required"
assets = [
    ["target/release/meilies-server", "/usr/local/bin", "755"]
]
