[package]
name = "meilies-server"
version = "0.1.0"
authors = ["Kerollmops <renault.cle@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
bytes = "0.4.11"
futures = "0.1.25"
log = "0.4.6"
meilies = { version = "0.1", path = "../meilies" }
sled = "0.18.1"
tokio = "0.1.16"
env_logger = "0.6.0"
