[package]
name = "meilies-client"
version = "0.1.0"
authors = ["Kerollmops <renault.cle@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6.0"
log = "0.4.6"
meilies = { version = "0.1", path = "../meilies" }
tokio = "0.1.16"
futures = "0.1.25"
